name: my_tank
description: My Code Tank

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  shelf_router: ^1.1.3
  codetanks:
    git:
      url: https://github.com/code-tanks/dart-api.git

dev_dependencies:
  shelf_test_handler: ^2.0.1
  test: ^1.21.4
